import "@components/footer/footer.scss"
import "@components/footer/__main-content/__main-content.js"
import "@components/footer/__social-content/__social-content.js"
import "@components/footer/__small-footer/__small-footer.js"
import "@components/text-field/text-field.js"
